# -*- coding: utf-8 -*-
"""linear_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jf7AB-kJFjGuqHHLVDLA-MWiecfKCl2c
"""

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


class Linear_Regression():
    """
    Custom Linear Regression implementation using NumPy.

    Parameters
    ----------
    l2 : float, default=0.001
        L2 regularization strength.

    alpha : float, default=0.001
        Learning rate for gradient descent.

    iter : int, default=100
        Number of training epochs.
    """

    def __init__(self, l2: float = 0.001, alpha: float = 0.001, iter: int = 100) -> None:
        self.l2 = l2
        self.alpha = alpha
        self.iter = iter

    def forward(self, w: np.ndarray, b: float, x: np.ndarray) -> np.ndarray:
        """
        Forward pass of linear regression.

        Parameters
        ----------
        w : np.ndarray
            Weight vector of shape (n_features,)

        b : float
            Bias term

        x : np.ndarray
            Input feature matrix of shape (m, n_features)

        Returns
        -------
        np.ndarray
            Predicted values
        """
        pred = x @ w + b
        return pred

    def compute_cost(self, w: np.ndarray, b: float, x: np.ndarray, y: np.ndarray):
        """
        Compute Mean Squared Error cost.

        Returns
        -------
        pred : np.ndarray
            Model predictions

        cost : float
            MSE loss
        """
        y = np.asarray(y).flatten()
        pred = self.forward(w, b, x)
        m = len(y)
        cost = (1 / m) * np.sum((pred - y) ** 2)
        return pred, cost

    def compute_gradients(self, pred: np.ndarray, w: np.ndarray, x: np.ndarray, y: np.ndarray, l2: float):
        """
        Compute gradients for weights and bias.

        Returns
        -------
        dj_dw : np.ndarray
            Gradient w.r.t weights

        dj_db : float
            Gradient w.r.t bias
        """
        y = np.asarray(y).flatten()
        pred = np.asarray(pred).flatten()
        m = len(y)
        dj_dw = (2 / m) * (x.T @ (pred - y)) + (2 * l2 / m) * w
        dj_db = (2 / m) * np.sum(pred - y)
        return dj_dw, dj_db

    def cosine_scheduler(self, epoch: int, total_epochs: int, alpha: float, alpha_min: float = 0.00001) -> float:
        """
        Cosine learning rate scheduler.

        Parameters
        ----------
        epoch : int
            Current epoch

        total_epochs : int
            Total training epochs

        alpha : float
            Initial learning rate

        alpha_min : float
            Minimum learning rate

        Returns
        -------
        float
            Adjusted learning rate
        """
        return alpha_min + 0.5 * (alpha - alpha_min) * (1 + np.cos(np.pi * epoch / total_epochs))

    def fit(
        self,
        x: np.ndarray | pd.DataFrame,
        y: np.ndarray | pd.Series,
        freeze: float = 0.15,
        random_state: int = 42,
        verbose: int = 0,
        history_save_interval: int = 10,
        cosine_annealing: bool = False,
        normalise: bool = True
    ) -> None:
        """
        Train the Linear Regression model using gradient descent.

        Parameters
        ----------
        x : array-like or DataFrame
            Training feature matrix

        y : array-like or Series
            Target values

        freeze : float
            Sleep time between verbose prints

        random_state : int
            Random seed for weight initialization

        verbose : int
            Print training cost every `verbose` epochs

        history_save_interval : int
            Epoch interval to save cost history

        cosine_annealing : bool
            Whether to use cosine LR scheduler

        normalise : bool
            Whether to standardize input features
        """

        if isinstance(x, pd.DataFrame):
            self.train_features = x.columns
            x = x.values

        if isinstance(y, pd.Series):
            y = y.values

        y = np.asarray(y).flatten()

        self.y = y
        self.history_save_interval = history_save_interval
        self.n = x.shape[1]

        rs = np.random.RandomState(seed=random_state)

        w = rs.randn(self.n)
        b = 0.0

        self.cost_his = []
        self.weight_his = []
        self.lr_his = []

        self.m = x.shape[0]

        if normalise:
            self.scaler = StandardScaler()
            x = self.scaler.fit_transform(x)

        for epoch in range(self.iter):

            pred, cost = self.compute_cost(w, b, x, y)

            if cosine_annealing:
                lr = self.cosine_scheduler(epoch, self.iter, self.alpha)
                self.lr_his.append(lr)
            else:
                lr = self.alpha

            dj_dw, dj_db = self.compute_gradients(pred, w, x, y, self.l2)

            dj_dw = np.clip(dj_dw, -1e5, 1e5)
            dj_db = np.clip(dj_db, -1e5, 1e5)

            w -= lr * dj_dw
            b -= lr * dj_db

            if epoch % history_save_interval == 0:
                self.cost_his.append(cost)
                self.weight_his.append(w.copy())

            if verbose != 0:
                if epoch % verbose == 0 or epoch == self.iter - 1:
                    print(f"\033[1mEpoch: {epoch}, cost: {cost:.6f}\033[0m")
                    time.sleep(freeze)

            if epoch == self.iter - 1:
                self.last_cost = cost

        self.coefficients_ = w
        self.intercept_ = b

    def predict(self, test: np.ndarray | pd.DataFrame) -> np.ndarray:
        if isinstance(test, pd.DataFrame):
            test = test.values

        if hasattr(self, "scaler"):
            test = self.scaler.transform(test)

        if test.shape[1] != self.n:
            raise ValueError("Number of test features unequal to train features")

        return self.forward(self.coefficients_, self.intercept_, test)

    def plot_cost(self) -> None:
        epoch_axis = [self.history_save_interval * i for i in range(len(self.cost_his))]
        plt.figure(figsize=(8, 5))
        plt.plot(epoch_axis, self.cost_his)
        plt.xlabel("Epochs")
        plt.ylabel("Cost")
        plt.title("Epoch vs Cost")
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def feature_importance(self) -> pd.DataFrame:
        if hasattr(self, "train_features"):
            features = self.train_features
        else:
            features = [f"feature_{i}" for i in range(self.n)]
        coefs = self.coefficients_.flatten()
        return pd.DataFrame([coefs], columns=features)

    def coefficient_path(self) -> None:
        weights = np.array(self.weight_his)
        epochs = np.arange(len(weights)) * self.history_save_interval
        if hasattr(self, "train_features"):
            features = self.train_features
        else:
            features = [f"w{i}" for i in range(weights.shape[1])]
        plt.figure(figsize=(8, 5))
        for i in range(weights.shape[1]):
          plt.plot(epochs, weights[:, i], label=features[i], linewidth=2)
        plt.xlabel("Epoch")
        plt.ylabel("Coefficient Value")
        plt.title("Coefficient Paths During Training")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def lr_plot(self) -> None:
        if len(self.lr_his) != 0:
            x = list(range(len(self.lr_his)))
            plt.figure(figsize=(8, 5))
            plt.plot(x, self.lr_his)
            plt.xlabel("Epoch")
            plt.ylabel("LR")
            plt.title("Learning Rate During Training")
            plt.grid(True)
            plt.tight_layout()
            plt.show()

    def summary(self) -> None:
        print(f"\033[1mFeatures: {self.n}\nSamples: {self.m}\nEpochs: {self.iter}\nRegularization: L2({self.l2})\n\nFinal Cost: {self.last_cost:.6f}\nIntercept: {self.intercept_:.4f}\033[0m")

class Logistic_Regression():
    """
    Custom Logistic Regression implementation using NumPy.

    Parameters
    ----------
    l2 : float, default=0.001
        L2 regularization strength.

    alpha : float, default=0.001
        Learning rate for gradient descent.

    iter : int, default=100
        Number of training epochs.
    """

    def __init__(self, l2: float = 0.001, alpha: float = 0.001, iter: int = 100) -> None:
        self.l2 = l2
        self.alpha = alpha
        self.iter = iter

    def sigmoid(self, z: np.ndarray) -> np.ndarray:
        """
        Sigmoid activation function.
        """
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def forward(self, w: np.ndarray, b: float, x: np.ndarray) -> np.ndarray:
        """
        Forward pass of logistic regression.
        """
        return self.sigmoid(x @ w + b)

    def compute_cost(self, w: np.ndarray, b: float, x: np.ndarray, y: np.ndarray):
        """
        Compute binary cross-entropy loss.
        """
        y = np.asarray(y).flatten()
        pred = self.forward(w, b, x)

        m = len(y)

        pred = np.clip(pred, 1e-8, 1 - 1e-8)

        cost = -(1/m) * np.sum(
            y * np.log(pred) +
            (1 - y) * np.log(1 - pred)
        )

        return pred, cost

    def compute_gradients(
        self,
        pred: np.ndarray,
        w: np.ndarray,
        x: np.ndarray,
        y: np.ndarray,
        l2: float
    ):
        """
        Compute gradients of weights and bias.
        """
        y = np.asarray(y).flatten()
        pred = np.asarray(pred).flatten()

        m = len(y)

        dj_dw = (1/m) * (x.T @ (pred - y)) + (2*l2/m) * w
        dj_db = (1/m) * np.sum(pred - y)

        return dj_dw, dj_db

    def cosine_scheduler(
        self,
        epoch: int,
        total_epochs: int,
        alpha: float,
        alpha_min: float = 0.0001
    ) -> float:
        """
        Cosine learning rate scheduler.
        """
        return alpha_min + 0.5*(alpha-alpha_min)*(1+np.cos(np.pi*epoch/total_epochs))

    def fit(
        self,
        x: np.ndarray | pd.DataFrame,
        y: np.ndarray | pd.Series,
        freeze: float = 0.15,
        random_state: int = 42,
        verbose: int = 0,
        history_save_interval: int = 10,
        cosine_annealing: bool = False,
        normalise: bool = True
    ) -> None:
        """
        Train the Logistic Regression model using gradient descent.
        """

        if isinstance(x, pd.DataFrame):
            self.train_features = x.columns
            x = x.values

        if isinstance(y, pd.Series):
            y = y.values

        y = np.asarray(y).flatten()

        self.y = y
        self.history_save_interval = history_save_interval
        self.n = x.shape[1]

        rs = np.random.RandomState(seed=random_state)

        w = rs.randn(self.n)
        b = 0.0

        self.cost_his = []
        self.weight_his = []
        self.lr_his = []

        self.m = x.shape[0]

        if normalise:
            self.scaler = StandardScaler()
            x = self.scaler.fit_transform(x)

        self.train_X = x

        for epoch in range(self.iter):

            pred, cost = self.compute_cost(w, b, x, y)

            if cosine_annealing:
                lr = self.cosine_scheduler(epoch, self.iter, self.alpha)
            else:
                lr = self.alpha

            self.lr_his.append(lr)

            dj_dw, dj_db = self.compute_gradients(pred, w, x, y, self.l2)

            dj_dw = np.clip(dj_dw, -1e5, 1e5)
            dj_db = np.clip(dj_db, -1e5, 1e5)

            w -= lr * dj_dw
            b -= lr * dj_db

            if epoch % history_save_interval == 0:
                self.cost_his.append(cost)
                self.weight_his.append(w.copy())

            if verbose != 0:
                if epoch % verbose == 0 or epoch == self.iter - 1:
                    print(f"\033[1mEpoch: {epoch}, cost: {cost:.6f}\033[0m")
                    time.sleep(freeze)

            if epoch == self.iter - 1:
                self.last_cost = cost

        self.coefficients_ = w
        self.intercept_ = b

    def predict_proba(self, test: np.ndarray | pd.DataFrame) -> np.ndarray:
        """
        Predict class probabilities.
        """

        if isinstance(test, pd.DataFrame):
            test = test.values

        if hasattr(self, "scaler"):
            test = self.scaler.transform(test)

        if test.shape[1] != self.n:
            raise ValueError("Number of test features unequal to train features")

        prob = self.forward(self.coefficients_, self.intercept_, test)

        return np.vstack((1 - prob, prob)).T

    def predict(self, test: np.ndarray | pd.DataFrame, threshold: float = 0.5) -> np.ndarray:
        """
        Predict binary class labels.
        """
        prob = self.predict_proba(test)[:, 1]
        return (prob >= threshold).astype(int)

    def training_accuracy(self) -> None:
        """Print training accuracy."""

        pred_labels = self.predict(self.train_X)

        acc = np.mean(pred_labels == self.y) * 100

        print(f"\033[1mTrain Accuracy: {acc:.2f}%\033[0m")

    def plot_cost(self) -> None:
        """Plot training loss vs epochs."""

        epoch_axis = [i * self.history_save_interval for i in range(len(self.cost_his))]

        plt.figure(figsize=(8,5))
        plt.plot(epoch_axis, self.cost_his)

        plt.xlabel("Epochs")
        plt.ylabel("Cost")
        plt.title("Epoch vs Cost")

        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def feature_importance(self) -> pd.DataFrame:
        """
        Return feature coefficients.
        """

        if hasattr(self, "train_features"):
            features = self.train_features
        else:
            features = [f"feature_{i}" for i in range(self.n)]

        coefs = self.coefficients_.flatten()

        return pd.DataFrame([coefs], columns=features)

    def coefficient_path(self) -> None:
        """Plot coefficient values during training."""

        weights = np.array(self.weight_his)

        epochs = np.arange(len(weights)) * self.history_save_interval

        if hasattr(self, "train_features"):
            features = self.train_features
        else:
            features = [f"w{i}" for i in range(weights.shape[1])]

        plt.figure(figsize=(8,5))

        for i in range(weights.shape[1]):
            plt.plot(epochs, weights[:, i], label=features[i], linewidth=2)

        plt.xlabel("Epoch")
        plt.ylabel("Coefficient Value")
        plt.title("Coefficient Paths During Training")

        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def lr_plot(self) -> None:
        """Plot learning rate schedule."""

        if len(self.lr_his) != 0:

            plt.figure(figsize=(8,5))
            plt.plot(range(len(self.lr_his)), self.lr_his)

            plt.xlabel("Epoch")
            plt.ylabel("LR")
            plt.title("Learning Rate During Training")

            plt.grid(True)
            plt.tight_layout()
            plt.show()

    def summary(self) -> None:
        """Print model summary."""

        pred_labels = self.predict(self.train_X)

        acc = np.mean(pred_labels == self.y) * 100

        print(f"\033[1mFeatures: {self.n}\nSamples: {self.m}\nEpochs: {self.iter}\nRegularization: L2({self.l2})\n\nFinal Cost: {self.last_cost:.6f}\nIntercept: {self.intercept_:.4f}\nAccuracy: {acc:.2f}%\033[0m")